@startuml

actor Developer as D
box
participant Throttle as Tr
participant Queue as Q
end box
participant "Throttle\nStrategy" as TrS
participant Timer as T

group Developer thread
D -> Tr: execution request
Tr -> Tr: create task future
Tr -> Q: store future
D <- Tr: return future
end

group Loop in throttle thread
Tr <- Q: get next future
activate Tr
Tr -> TrS: ask execution permit
TrS -> T: ask current time
TrS <- T: return
TrS -> T: wait wait next execution time
...
TrS <-- T
Tr <-- TrS
Tr -> Tr: execute task
activate Tr #DarkSalmon
deactivate Tr

D <- Tr: return task result
deactivate Tr
end

@enduml